
local upgrades = {
    {
        name = "Coins per click",
        description = "Adds +1 coins per click",
        cost = 50,
        image = "pezh_cpc_1",
        type = "coins_per_click",
        action = "+",
        value = 1,
        cost_action = "*",
        cost_value = 1.5,
        upgraded = 0,
        max_upgrades = 5,
    },
    {
        name = "Coins per second",
        description = "Adds +0.5 coins per second",
        cost = 100,
        image = "pezh_cps_1",
        type = "coins_per_seconds",
        action = "+",
        value = 0.5,
        cost_action = "*",
        cost_value = 1.3,
        upgraded = 0,
        max_upgrades = 6,
    },
    {
        name = "Second hand",
        description = "Adds +2 coins per click",
        cost = 500,
        image = "pezh_cpc_2",
        type = "coins_per_click",
        action = "+",
        value = 2,
        cost_action = "*",
        cost_value = 1.4,
        upgraded = 0,
        max_upgrades = 6,
    },
    {
        name = "Coin factory",
        description = "Adds +1 coins per second",
        cost = 600,
        image = "pezh_cps_2",
        type = "coins_per_seconds",
        action = "+",
        value = 1,
        cost_action = "*",
        cost_value = 1.3,
        upgraded = 0,
        max_upgrades = 5,
    },
    {
        name = "Clicking faster",
        description = "Adds +4 coins per click",
        cost = 4000,
        image = "pezh_cpc_3",
        type = "coins_per_click",
        action = "+",
        value = 4,
        cost_action = "*",
        cost_value = 1.2,
        upgraded = 0,
        max_upgrades = 8,
    },
    {
        name = "Media coins",
        description = "Adds +3 coins per second",
        cost = 3000,
        image = "pezh_cps_3",
        type = "coins_per_seconds",
        action = "+",
        value = 1,
        cost_action = "*",
        cost_value = 1.3,
        upgraded = 0,
        max_upgrades = 5,
    },
    {
        name = "Fix the bugs",
        description = "I don't know what it does",
        cost = 12000,
        image = "debug",
        type = "coins_per_click",
        action = "*",
        value = 1.1,
        cost_action = "*",
        cost_value = 1.3,
        upgraded = 0,
        max_upgrades = 10,
    },
}

return upgrades